version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: jobportal-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: jobportal-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/jobportal?authSource=admin
      - SECRET_KEY=HarHarMahadev
      - CLOUD_NAME=dq8ariioz
      - API_KEY=858319527567711
      - API_SECRET=zvNVBmcA32j7XWdPaFJOeit-5ow

  mongo:
    image: mongo:6
    container_name: jobportal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

volumes:
  mongo_data:
